### ISSUE TITLE
Issues with 1.10 update on TRAC 1.4

### ISSUE THREAD

**Issue by a-lister** [seccanj/testman4trac#1]
We have installed the latest build on our install of TRAC 1.4.  We previously ran the older plugin without issue on TRAC 1.0.20

TRAC Version:  1.4.3
Test Manager Version:  1.10
Python Version:  2.7.15 64 bit

While the plugins install and show up correctly in the admin panel, something isn't quite right.  I'm not sure if it's our setup, or there are still some things in the plugin.

When going to admin >> Test Manager >> Settings.  There will just be a blank page.  The logs show the following:

`2022-02-15 09:27:30,118 Trac[chrome] ERROR: Jinja2 UndefinedError error while rendering XML/HTML template 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\trac\web\chrome.py", line 1706, in _iterable_jinja_content
    for chunk in stream:
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1357, in __next__
    return self._next()
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1334, in _buffered_generator
    c = next(self._gen)
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 1125, in generate
    yield self.environment.handle_exception()
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "E:\\Trac-Python-Eggs\testmanager-1.10.0-py2.7.egg-tmp\testmanager\templates\admin_settings.html", line 81, in top-level template code
    <td><input type="checkbox" name="testcatalog.${testcatalog_column['name']}" checked="${testcatalog_column['visible']=='True' or None}"/></td>
  File "C:\Python27\lib\site-packages\jinja2\environment.py", line 452, in getitem
    return obj[argument]
UndefinedError: 'testcatalog_column' is undefined`

I will try the latest plugin on our side testing copy of Test Manager running 1.0.20 and see if that plays nice for a test.

Other versions:
Genshi     0.7.1
Jinja2     2.11.3
MarkupSafe 1.1.1
pip        20.3.4
setuptools 44.1.1
Trac       1.4.3
wheel      0.32.3

update:  I tested this on a side copy running TRAC 1.0.20.  I am also having issues installing the updated TestManager plugin.  The previous release works fine.

**Comment by seccanj** [comment]
The previous releases were not compatibile with Trac 1.4 because of a mistake in setting up my test environment.

I've just fixed all incompatibilities with Trac 1.2 and with Trac 1.4 and cleaned up all the releases.

Now you will find that:
 * Releases 1.9.x are compatible with Trac 0.12.x.
 * Releases 1.20.x are compatible with Trac 1.2.x.
 * Releases 2.x are compatible with Trac 1.4.x.

Unfortunately there is currently no release compatible with Trac 1.5, because of the dropped support of Genshi, a technology the plugins are heavily based on.

Please, refer to the releases page for the available downloads: https://github.com/seccanj/testman4trac/releases
